const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('huistrap', {
  check: () => ipcRenderer.invoke('huistrap:check'),
  launchInstalled: () => ipcRenderer.invoke('huistrap:launch-installed'),
  downloadAndLaunch: () => ipcRenderer.invoke('huistrap:download-and-launch'),
  launchStudio: () => ipcRenderer.invoke('huistrap:launch-studio'),
  onProgress: (cb) => ipcRenderer.on('huistrap:progress', (_e, data) => cb(data)),
  closeApp: () => ipcRenderer.invoke('huistrap:close'),
  onProtocolLaunchStarted: (cb) => ipcRenderer.on('huistrap:protocol-launch-started', () => cb()),
  onProtocolLaunchDownloading: (cb) => ipcRenderer.on('huistrap:protocol-launch-downloading', () => cb()),
  onProtocolLaunchDone: (cb) => ipcRenderer.on('huistrap:protocol-launch-done', () => cb()),
  onProtocolLaunchFailed: (cb) => ipcRenderer.on('huistrap:protocol-launch-failed', (_e, message) => cb(message)),
  onProtocolUpdateAvailable: (cb) => ipcRenderer.on('huistrap:protocol-update-available', (_e, data) => cb(data)),
  protocolDownloadAndLaunch: () => ipcRenderer.invoke('huistrap:protocol-download-and-launch'),
  protocolLaunchCurrent: () => ipcRenderer.invoke('huistrap:protocol-launch-current'),
  protocolCancel: () => ipcRenderer.invoke('huistrap:protocol-cancel'),

  getSettings: () => ipcRenderer.invoke('huistrap:get-settings'),
  setChannel: (channel) => ipcRenderer.invoke('huistrap:set-channel', channel),
  setConcurrency: (value) => ipcRenderer.invoke('huistrap:set-concurrency', value),
  setFpsCap: (value) => ipcRenderer.invoke('huistrap:set-fps-cap', value),
  setCursor: (cursorType) => ipcRenderer.invoke('huistrap:set-cursor', cursorType),
  setActivityTray: (enabled) => ipcRenderer.invoke('huistrap:set-activity-tray', enabled),
  setFflags: (flags) => ipcRenderer.invoke('huistrap:set-fflags', flags),
  onShowHome: (cb) => ipcRenderer.on('huistrap:show-home', () => cb()),
  changeVersionsDir: () => ipcRenderer.invoke('huistrap:change-versions-dir'),
  openVersionsDir: () => ipcRenderer.invoke('huistrap:open-versions-dir'),
  changeStudioVersionsDir: () => ipcRenderer.invoke('huistrap:change-studio-versions-dir'),
  openStudioVersionsDir: () => ipcRenderer.invoke('huistrap:open-studio-versions-dir'),
  chooseCustomFont: () => ipcRenderer.invoke('huistrap:choose-custom-font'),
  clearCustomFont: () => ipcRenderer.invoke('huistrap:clear-custom-font'),
  onMigrationProgress: (cb) => ipcRenderer.on('huistrap:migration-progress', (_e, data) => cb(data)),
  resizeHome: () => ipcRenderer.invoke('huistrap:resize-home'),
  resizeFlow: () => ipcRenderer.invoke('huistrap:resize-flow'),
  resizeModal: () => ipcRenderer.invoke('huistrap:resize-modal'),
  resizeCredits: () => ipcRenderer.invoke('huistrap:resize-credits'),
  resizeSettings: () => ipcRenderer.invoke('huistrap:resize-settings'),
  resizeAccounts: () => ipcRenderer.invoke('huistrap:resize-accounts'),
  checkAppUpdateNow: () => ipcRenderer.invoke('huistrap:check-app-update-now'),
  getPendingAppUpdate: () => ipcRenderer.invoke('huistrap:get-pending-app-update'),
  installAppUpdate: () => ipcRenderer.invoke('huistrap:install-app-update'),
  onAppUpdateAvailable: (cb) => ipcRenderer.on('huistrap:app-update-available', (_e, version) => cb(version)),
  onAppUpdateFound: (cb) => ipcRenderer.on('huistrap:app-update-found', (_e, version) => cb(version)),
  onAppUpdateFailed: (cb) => ipcRenderer.on('huistrap:app-update-failed', (_e, message) => cb(message)),
  getPendingChangelog: () => ipcRenderer.invoke('huistrap:get-pending-changelog'),
  markChangelogShown: () => ipcRenderer.invoke('huistrap:mark-changelog-shown'),
  previewChangelog: () => ipcRenderer.invoke('huistrap:preview-changelog'),

  accountsList: () => ipcRenderer.invoke('huistrap:accounts-list'),
  accountsAdd: () => ipcRenderer.invoke('huistrap:accounts-add'),
  accountsRemove: (userId) => ipcRenderer.invoke('huistrap:accounts-remove', userId),
  accountsReorder: (orderedUserIds) => ipcRenderer.invoke('huistrap:accounts-reorder', orderedUserIds),
  accountsLaunch: (userId, options) => ipcRenderer.invoke('huistrap:accounts-launch', userId, options),
  accountsOpenBrowser: (userId) => ipcRenderer.invoke('huistrap:accounts-open-browser', userId),
  accountsPresence: () => ipcRenderer.invoke('huistrap:accounts-presence'),
  accountsKill: (userId) => ipcRenderer.invoke('huistrap:accounts-kill', userId),
  instancesList: () => ipcRenderer.invoke('huistrap:instances-list'),
  onInstancesUpdate: (cb) => ipcRenderer.on('huistrap:instances-update', (_e, instances) => cb(instances)),
  onAccountLaunchDownloading: (cb) => ipcRenderer.on('huistrap:account-launch-downloading', () => cb()),

  savedGamesList: () => ipcRenderer.invoke('huistrap:saved-games-list'),
  savedGamesSave: (placeId, name) => ipcRenderer.invoke('huistrap:saved-games-save', placeId, name),
  savedGamesRename: (id, name) => ipcRenderer.invoke('huistrap:saved-games-rename', id, name),
  savedGamesRemove: (id) => ipcRenderer.invoke('huistrap:saved-games-remove', id),

  openDiscord: () => ipcRenderer.invoke('huistrap:open-discord'),

  getExploits: () => ipcRenderer.invoke('huistrap:get-exploits'),
  setSelectedExploit: (title) => ipcRenderer.invoke('huistrap:set-selected-exploit', title),
  getExploitStatus: () => ipcRenderer.invoke('huistrap:get-exploit-status')
});
